"""Database createee

Revision ID: 068ff82e3762
Revises: 4c9dda00d725
Create Date: 2023-06-20 18:09:00.860371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068ff82e3762'
down_revision = '4c9dda00d725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
