"""Database creation

Revision ID: 3b54393463aa
Revises: a325ae122e39
Create Date: 2023-06-20 17:14:13.176438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b54393463aa'
down_revision = 'a325ae122e39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
