"""Database createee

Revision ID: 4c9dda00d725
Revises: 5e3866332962
Create Date: 2023-06-20 18:08:40.869829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9dda00d725'
down_revision = '5e3866332962'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
