"""Database createee

Revision ID: 711e19c98cc6
Revises: 2f050cb83002
Create Date: 2023-06-20 17:52:18.414484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711e19c98cc6'
down_revision = '2f050cb83002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
