"""Database creation

Revision ID: a325ae122e39
Revises: 106fa2276cbc
Create Date: 2023-06-20 17:13:38.750635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a325ae122e39'
down_revision = '106fa2276cbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
