"""Database createeasdadas

Revision ID: a3cc79968281
Revises: 068ff82e3762
Create Date: 2023-06-20 18:09:09.181119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cc79968281'
down_revision = '068ff82e3762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
